### ISSUE TITLE
ModuleNotFoundError: No module named 'parsers'

### ISSUE THREAD

**Issue by enribd** [BrunoSilvaAndrade/python-json-config-parser#22]
Hi,

first of all, nice library!. I've been using it for a couple of days on a personal project and it's working great aside from the following error:

```bash
root@b3b7d8677bcc:/# pip install python-config-parser
Collecting python-config-parser
  Downloading python_config_parser-3.1.0-py3-none-any.whl (5.7 kB)
Collecting PyYaml>=3.12.0
  Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 kB 14.5 MB/s eta 0:00:00
Collecting schema>=0.7.1
  Downloading schema-0.7.5-py2.py3-none-any.whl (17 kB)
Collecting contextlib2>=0.5.5
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Installing collected packages: PyYaml, contextlib2, schema, python-config-parser
Successfully installed PyYaml-6.0 contextlib2-21.6.0 python-config-parser-3.1.0 schema-0.7.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv


root@b3b7d8677bcc:/# python
Python 3.9.13 (main, Jul 12 2022, 12:11:13)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyconfigparser import configparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyconfigparser.py", line 1, in <module>
    from parsers import ParseError, json_parser, yaml_parser
ModuleNotFoundError: No module named 'parsers'
```

I have tested the installation in the official python docker images: python:3.9-slim and python:3.10-slim with the same result.

I think the file parsers.py of your library is not being added to the final package. I'm no expert in packaging python modules so I cannot help you much further (I can test the fix when you have it ready if you will). I'm sure it's just a little error, or maybe I am doing anything wrong, if it's that just let me know and I'll try.

Thanks!

**Comment by BrunoSilvaAndrade** [comment]
Hi, thank you for the congrats,  I'm sorry for the delay, I'll check this, that's kinda strange cause,  I have a step on action to validate the package,  I'll re-produce this test that you did and I'll try to fix this problem.

**Comment by BrunoSilvaAndrade** [comment]
This Issue has been fixed, the whole implementation has been unified in the pyconfigparser.py
